name: deploy contact form to AWS lambda
on:
    push:
        branches:
            - move-contact-to-lambda
jobs:
    lambda:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Find modified files
              id: changed-files
              uses: tj-actions/changed-files@v41

            - name: Check for changes to contact form code
              id: check-changes
              env:
                ALL_CHANGED_FILES: ${{ steps.changed-files.outputs.all_changed_files }}
              # note: this is a bash script - could be put in separate .sh file
              run: |
                if [[ ${ALL_CHANGED_FILES[@]} =~ "contact-form/lambda.py" ]]
                then 
                  echo file_changed=true >> $GITHUB_OUTPUT
                else 
                  echo file_changed=false >> $GITHUB_OUTPUT
                fi

            - name: Upload changes
              env:
                CHANGED: ${{ steps.check-changes.outputs.file_changed }}
              if: steps.check-changes.outputs.file_changed == true
              run: echo ${CHANGED}