name: deploy contact form to AWS lambda
on:
    push:
        branches:
            - move-contact-to-lambda
jobs:
    lambda:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Find modified files
              id: changed-files
              uses: tj-actions/changed-files@v41

            - name: Check for changes to contact form code
              id: check-changes
              env:
                ALL_CHANGED_FILES: ${{ steps.changed-files.outputs.all_changed_files }}
              # note: this is a bash script - could be put in separate .sh file
              run: echo file_changed=[[ ${ALL_CHANGED_FILES[@]} =~ "contact-form/lambda.py" ]] >> $GITHUB_OUTPUT

            - name: Upload changes
              env: 
                FILE_CHANGED: ${{ steps.check-changes.outputs.FILE_CHANGED }}
              if: ${FILE_CHANGED}
              run: echo steps.check-changes.outputs.FILE_CHANGED