name: deploy contact form to AWS lambda
on:
    push:
        branches:
            - move-contact-to-lambda
jobs:
    lambda:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Get changed files
              id: changed-files
              uses: tj-actions/changed-files@v41

            - name: List all changed files
              env:
                ALL_CHANGED_FILES: ${{ steps.changed-files.outputs.all_changed_files }}
              # note: this is a bash script - could be put in separate .sh file
              run: |
                if [[ ${ALL_CHANGED_FILES[@]} =~ "contact-form/lambda.py" ]]
                then
                  echo "File modified"
                else
                  echo "file unchanged"
                fi