name: deploy contact form to AWS lambda
on:
    push:
        branches:
            - move-contact-to-lambda
jobs:
   Deploy-Contact:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Find modified files
              id: changed-files
              uses: tj-actions/changed-files@v41

            - name: Check for changes to contact form code
              id: check-changes
              env:
                ALL_CHANGED_FILES: ${{ steps.changed-files.outputs.all_changed_files }}
              # note: this is a bash script - could be put in separate .sh file
              run: |
                if [[ ${ALL_CHANGED_FILES[@]} =~ "contact-form/lambda.py" ]]
                then 
                  echo file_changed=1 >> $GITHUB_OUTPUT
                else 
                  echo file_changed=0 >> $GITHUB_OUTPUT
                fi

            - name: test
              env:
                CHANGED: ${{ steps.check-changes.outputs.file_changed }}
              run: echo ${CHANGED}


            - name: Configure AWS
              uses: aws-actions/configure-aws-credentials@v2
              if: steps.check-changes.outputs.file_changed == true
              with:
                aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
                aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                aws-region: eu-west-2

            - name: Deploy changes
              env:
                CHANGED: ${{ steps.check-changes.outputs.file_changed }}
              if: steps.check-changes.outputs.file_changed == true
              run: |
                zip -j contact_form.zip ./contact-form/lambda.py
                aws lambda update-function-code --function-name=BWS-contact --zip-file=fileb://contact_form.zip